# Generated by Django 5.2.5 on 2025-08-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiepilogoAnnuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField()),
                ('reddito_lordo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reddito_netto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imposte_versate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rimborso_ottenuto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('potenziale_rimborso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dati_simulati', models.BooleanField(default=True)),
                ('dati_anagrafici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riepiloghi', to='anagrafica.datianagrafici')),
            ],
            options={
                'ordering': ['anno'],
                'unique_together': {('dati_anagrafici', 'anno')},
            },
        ),
    ]
