"""
Django settings for djcore project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Caricamento Variabili d'Ambiente ---
ENV_FILE = BASE_DIR.parent / ".env"
env = environ.Env()

if ENV_FILE.exists():
    environ.Env.read_env(str(ENV_FILE))
    print("✅ File .env caricato da:", ENV_FILE)
else:
    print("⚠️  Nessun file .env trovato in:", ENV_FILE)

# --- Impostazioni di Sicurezza e Core ---
SECRET_KEY = env('DJANGO_SECRET_KEY')
DEBUG = env.bool('DEBUG', default=True)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Aggiunge il dominio di DigitalOcean in produzione per evitare errori 400
if not DEBUG:
    ALLOWED_HOSTS.append('.ondigitalocean.app')

# --- Definizione delle Applicazioni ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'declaration_app',
    'anagrafica',
    'django_vite',
    'corsheaders',
    'riepilogo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'djcore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djcore.wsgi.application'


# --- Database ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# --- Validazione Password ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Internazionalizzazione ---
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- Gestione File Statici e Integrazione Vite ---
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Configurazione dice a 'collectstatic' di cercare gli asset generati da Vite

STATICFILES_DIRS = [
    BASE_DIR.parent / "frontend/dist",
]

# La cartella (all'interno del backend) dove 'collectstatic' depositerà tutti i file statici
STATIC_ROOT = BASE_DIR / 'staticfiles'

# In sviluppo, il manifest è nella sua posizione originale.
VITE_MANIFEST_PATH = BASE_DIR / "frontend/dist/manifest.json"

# In produzione (not DEBUG), 'collectstatic' avrà copiato il manifest dentro STATIC_ROOT
if not DEBUG:
    VITE_MANIFEST_PATH = STATIC_ROOT / "manifest.json"

DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "manifest_path": VITE_MANIFEST_PATH, # Usa il percorso dinamico
        "dev_server_host": "127.0.0.1",
        "dev_server_port": 5173,
    }
}


# --- URL di Autenticazione ---
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# --- Tipo di Chiave Primaria ---
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
